(function (root, factory) {
    const api = factory();
    if (typeof module !== 'undefined' && module.exports) module.exports = api;
    else root.CvModel = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
    'use strict';

    const templates = [
        { id: 'classic', name: 'Classic', role: 'backend', level: 'lateral', family: 'Essential', layout: 'single', font: 'Lato', heading: 'rule', header: 'left', color: '#176b5b', density: 'regular', description: 'Single-column, familiar section order, restrained rules.' },
        { id: 'compact', name: 'Compact', role: 'full-stack', level: 'lateral', family: 'Essential', layout: 'single', font: 'Lato', heading: 'plain', header: 'left', color: '#273541', density: 'compact', description: 'Tighter spacing for a concise engineering resume.' },
        { id: 'centered', name: 'Centered', role: 'frontend', level: 'lateral', family: 'Essential', layout: 'single', font: 'Lato', heading: 'rule', header: 'center', color: '#273541', density: 'regular', description: 'Centered identity above a clear chronological document.' },
        { id: 'minimal', name: 'Minimal', role: 'security', level: 'experienced', family: 'Essential', layout: 'single', font: 'Lato', heading: 'plain', header: 'left', color: '#273541', density: 'airy', description: 'Typography and whitespace, without decorative elements.' },
        { id: 'graduate', name: 'Graduate', role: 'graduate', level: 'fresher', family: 'Early Career', layout: 'single', font: 'Lato', heading: 'label', header: 'left', color: '#245ca7', density: 'regular', description: 'Distinct section labels for education and project evidence.' },
        { id: 'research', name: 'Research', role: 'research', level: 'academic', family: 'Academic', layout: 'single', font: 'PlexSerif', heading: 'rule', header: 'center', color: '#273541', density: 'regular', description: 'Serif typography suited to research and publications.' },
        { id: 'scholar', name: 'Scholar', role: 'research', level: 'academic', family: 'Academic', layout: 'single', font: 'PlexSerif', heading: 'plain', header: 'left', color: '#574144', density: 'airy', description: 'An open academic CV that grows across pages.' },
        { id: 'executive', name: 'Executive', role: 'engineering-manager', level: 'manager', family: 'Leadership', layout: 'single', font: 'PlexSerif', heading: 'label', header: 'left', color: '#273541', density: 'regular', description: 'People leadership, delivery ownership, and organizational outcomes.' },
        { id: 'principal', name: 'Principal', role: 'principal', level: 'experienced', family: 'Experienced', layout: 'single', font: 'Lato', heading: 'rule', header: 'left', color: '#245ca7', density: 'airy', description: 'Cross-team architecture, engineering judgment, and technical influence.' },
        { id: 'technical', name: 'Technical', role: 'systems', level: 'experienced', family: 'Engineering', layout: 'single', font: 'Lato', heading: 'label', header: 'left', color: '#176b5b', density: 'compact', description: 'Compact labels that keep technical evidence easy to scan.' },
        { id: 'ledger', name: 'Ledger', role: 'data', level: 'lateral', family: 'Engineering', layout: 'single', font: 'PlexSerif', heading: 'rule', header: 'left', color: '#245ca7', density: 'compact', description: 'A structured serif layout for detailed technical careers.' },
        { id: 'signal', name: 'Signal', role: 'platform', level: 'experienced', family: 'Engineering', layout: 'single', font: 'Lato', heading: 'band', header: 'left', color: '#a14337', density: 'regular', description: 'Lightly tinted headings with a clear single reading order.' },
        { id: 'folio', name: 'Folio', role: 'mobile', level: 'lateral', family: 'Portfolio', layout: 'single', font: 'PlexSerif', heading: 'band', header: 'center', color: '#176b5b', density: 'regular', description: 'Editorial type with subtle section highlights.' },
        { id: 'split', name: 'Split', role: 'ml', level: 'lateral', family: 'Two Column', layout: 'split', font: 'Lato', heading: 'rule', header: 'left', color: '#245ca7', density: 'regular', description: 'Skills and education beside the experience narrative.' },
        { id: 'sidebar', name: 'Sidebar', role: 'full-stack', level: 'lateral', family: 'Two Column', layout: 'sidebar', font: 'Lato', heading: 'label', header: 'left', color: '#176b5b', density: 'regular', description: 'A tinted side column for supporting credentials.' },
        { id: 'duet', name: 'Duet', role: 'backend', level: 'lateral', family: 'Two Column', layout: 'split', font: 'PlexSerif', heading: 'plain', header: 'center', color: '#574144', density: 'airy', description: 'Serif contrast and a two-column supporting section.' },
        { id: 'internship', name: 'First Internship', role: 'intern', level: 'fresher', family: 'Early Career', layout: 'single', font: 'Lato', heading: 'rule', header: 'center', color: '#245ca7', density: 'compact', description: 'Coursework, student projects, volunteering, and a first internship.' },
        { id: 'project-first', name: 'Project First', role: 'graduate', level: 'fresher', family: 'Portfolio', layout: 'single', font: 'Lato', heading: 'band', header: 'left', color: '#166875', density: 'regular', projectFirst: true, description: 'A project-led fresher CV with implementation, tests, and public artifacts.' },
        { id: 'business-case', name: 'Business Case', role: 'business-analyst', level: 'lateral', family: 'Essential', layout: 'single', font: 'PlexSerif', heading: 'rule', header: 'left', color: '#574144', density: 'regular', description: 'Requirements, stakeholder decisions, process analysis, and acceptance criteria.' },
        { id: 'career-switch', name: 'Career Transition', role: 'career-change', level: 'lateral', family: 'Essential', layout: 'single', font: 'Lato', heading: 'label', header: 'left', color: '#a14337', density: 'regular', projectFirst: true, description: 'Transferable experience alongside recent engineering projects and training.' },
        { id: 'senior', name: 'Senior Engineer', role: 'lead', level: 'experienced', family: 'Experienced', layout: 'single', font: 'Lato', heading: 'rule', header: 'left', color: '#273541', density: 'regular', nameRule: true, description: 'A chronological CV for senior ICs: decisions, delivery, mentoring, and ownership.' },
        { id: 'manager', name: 'Engineering Manager', role: 'engineering-manager', level: 'manager', family: 'Leadership', layout: 'single', font: 'Lato', heading: 'band', header: 'left', color: '#176b5b', density: 'regular', nameRule: true, description: 'Team scope, hiring, coaching, product partnership, and engineering delivery.' },
        { id: 'director', name: 'Engineering Director', role: 'director', level: 'manager', family: 'Leadership', layout: 'single', font: 'PlexSerif', heading: 'rule', header: 'center', color: '#273541', density: 'regular', description: 'Multi-team strategy, operating models, portfolio choices, and leadership development.' },
        { id: 'product', name: 'Product Narrative', role: 'product-manager', level: 'experienced', family: 'Leadership', layout: 'split', font: 'Lato', heading: 'label', header: 'left', color: '#a14337', density: 'regular', sideRight: true, description: 'Customer discovery, prioritization, experiments, and product outcomes.' },
        { id: 'analyst', name: 'Data Story', role: 'analyst', level: 'lateral', family: 'Engineering', layout: 'single', font: 'Lato', heading: 'band', header: 'left', color: '#245ca7', density: 'compact', description: 'SQL analysis, data quality, dashboards, and decisions supported by evidence.' },
        { id: 'quality', name: 'Quality Engineer', role: 'qa', level: 'lateral', family: 'Engineering', layout: 'single', font: 'Lato', heading: 'rule', header: 'left', color: '#166875', density: 'compact', description: 'Test design, automation, defect prevention, CI reliability, and release risk.' },
        { id: 'portrait', name: 'Portfolio Portrait', role: 'designer', level: 'lateral', family: 'Photo', layout: 'split', font: 'PlexSerif', heading: 'plain', header: 'left', color: '#a14337', density: 'regular', photo: 'left', sideRight: true, description: 'An optional portrait and portfolio-focused product design case studies.' },
        { id: 'profile', name: 'Professional Profile', role: 'cloud', level: 'experienced', family: 'Photo', layout: 'single', font: 'Lato', heading: 'rule', header: 'left', color: '#166875', density: 'regular', photo: 'right', nameRule: true, description: 'Cloud architecture and client delivery with an optional profile photograph.' },
        { id: 'photo-graduate', name: 'Graduate Profile', role: 'graduate', level: 'fresher', family: 'Photo', layout: 'single', font: 'Lato', heading: 'label', header: 'left', color: '#245ca7', density: 'compact', photo: 'right', description: 'Education and project detail with an optional photograph when appropriate for the application.' },
        { id: 'photo-manager', name: 'Leadership Profile', role: 'engineering-manager', level: 'manager', family: 'Photo', layout: 'sidebar', font: 'PlexSerif', heading: 'label', header: 'left', color: '#176b5b', density: 'regular', photo: 'left', description: 'A profile-led management CV with team leadership and delivery evidence.' },
        { id: 'bajaj-clean', name: 'Bajaj Clean', role: 'backend', level: 'lateral', family: 'Community', layout: 'single', font: 'PlexSerif', heading: 'rule', header: 'left', color: '#273541', density: 'compact', source: 'bajaj', description: 'An adaptation of Sourabh Bajaj\'s MIT-licensed single-column software resume format.' },
        { id: 'bajaj-editorial', name: 'Bajaj Editorial', role: 'technical-writer', level: 'experienced', family: 'Community', layout: 'single', font: 'PlexSerif', heading: 'rule', header: 'left', color: '#273541', density: 'regular', source: 'bajaj', description: 'The licensed single-column format adapted for technical writing and documentation portfolios.' }
    ];

    const roles = [
        { id: 'graduate', name: 'Student / New Graduate', headline: 'Software Engineering Graduate', focus: 'Lead with education and substantial projects when professional experience is limited. Explain your own implementation, tests, and constraints.', skills: 'Languages: Python, Java, SQL\nFoundations: Data structures, operating systems, networking\nTools: Git, pytest, Linux', project: 'Campus Study Planner', projectLine: 'Built a course-planning tool with prerequisite validation and tests for conflicting schedules.', experience: 'Software Engineering Intern', experienceLine: 'Added input-validation tests and documented a reproducible local development workflow.', educationFirst: true },
        { id: 'backend', name: 'Backend Engineering', headline: 'Backend Software Engineer', focus: 'Show API contracts, data ownership, correctness, reliability, and operational responsibility. Include measured outcomes only when you can substantiate them.', skills: 'Languages: Python, TypeScript, SQL\nBackend: REST APIs, PostgreSQL, Redis\nTools: Docker, Git, automated testing', project: 'Reliable Task Service', projectLine: 'Implemented idempotent task creation and worker-restart recovery with integration tests.', experience: 'Software Engineer', experienceLine: 'Implemented an API change with schema validation, migration tests, and documented failure handling.' },
        { id: 'frontend', name: 'Frontend Engineering', headline: 'Frontend Engineer', focus: 'Describe user workflows, accessibility, state management, tested behavior, and measured performance. Distinguish visual polish from product and engineering outcomes.', skills: 'Languages: TypeScript, JavaScript, HTML, CSS\nFrontend: React, accessibility, responsive design\nTools: Playwright, Git, browser profiling', project: 'Accessible Project Dashboard', projectLine: 'Built keyboard-accessible filtering and tested responsive layouts and empty states.', experience: 'Frontend Engineer', experienceLine: 'Delivered a reusable form workflow with validation, error recovery, and automated interaction tests.' },
        { id: 'full-stack', name: 'Full-Stack Engineering', headline: 'Full-Stack Software Engineer', focus: 'Explain one complete user journey across UI, API, and database. Be specific about ownership and avoid listing every framework you have briefly tried.', skills: 'Languages: TypeScript, Python, SQL\nStack: React, Node.js, PostgreSQL\nPractices: API design, testing, CI/CD', project: 'Appointment Booking Service', projectLine: 'Connected a booking interface to transactional availability checks and a tested cancellation flow.', experience: 'Full-Stack Engineer', experienceLine: 'Implemented a feature across the client and service layers with contract and regression tests.' },
        { id: 'mobile', name: 'Mobile Engineering', headline: 'Mobile Software Engineer', focus: 'Emphasize lifecycle, offline behavior, accessibility, battery/network considerations, releases, and crash diagnosis relevant to your actual platform experience.', skills: 'Languages: Kotlin, Swift\nMobile: Android, iOS, offline synchronization\nPractices: UI tests, profiling, release validation', project: 'Offline Reading App', projectLine: 'Implemented versioned local storage and a conflict-aware synchronization flow for saved articles.', experience: 'Mobile Engineer', experienceLine: 'Added lifecycle-aware request cancellation and tests for interrupted navigation and network recovery.' },
        { id: 'platform', name: 'Platform / SRE', headline: 'Platform and Reliability Engineer', focus: 'Show service ownership, observability, capacity, automation, and incident learning. State the workload and method behind reliability or latency claims.', skills: 'Languages: Go, Python, Bash\nPlatform: Linux, containers, Kubernetes\nReliability: Observability, incident response, CI/CD', project: 'Service Health Monitor', projectLine: 'Built a local monitoring demo with explicit health checks, alert thresholds, and a recovery runbook.', experience: 'Platform Engineer', experienceLine: 'Improved a deployment workflow with readiness checks, rollback validation, and structured logs.' },
        { id: 'data', name: 'Data Engineering', headline: 'Data Engineer', focus: 'Make data grain, quality, lineage, orchestration, backfills, and recovery visible. Distinguish a pipeline prototype from production-scale operation.', skills: 'Languages: Python, SQL\nData: PostgreSQL, batch pipelines, data modeling\nPractices: Data quality, orchestration, lineage', project: 'Versioned Analytics Pipeline', projectLine: 'Created an incremental pipeline with duplicate-event handling and reproducible backfill tests.', experience: 'Data Engineer', experienceLine: 'Added schema and freshness checks to a data transformation workflow and documented recovery steps.' },
        { id: 'ml', name: 'AI / ML Engineering', headline: 'Machine Learning Engineer', focus: 'State the prediction problem, valid split, baseline, metric, and deployment constraints. Avoid unsupported accuracy figures or claims that omit leakage and evaluation details.', skills: 'Languages: Python, SQL\nML: scikit-learn, PyTorch, model evaluation\nSystems: Feature pipelines, serving, experiment tracking', project: 'Document Retrieval Evaluation', projectLine: 'Compared lexical and vector retrieval on a versioned query set with separate relevance and latency measurements.', experience: 'ML Engineer', experienceLine: 'Built a reproducible baseline and checked feature timing, data leakage, and evaluation consistency.' },
        { id: 'security', name: 'Security Engineering', headline: 'Security Engineer', focus: 'Describe authorized defensive work, risk reduction, secure design, and validation. Never publish customer vulnerabilities, secrets, or confidential incident details.', skills: 'Languages: Python, Go\nSecurity: Threat modeling, application security, IAM\nPractices: Secure review, testing, incident analysis', project: 'API Authorization Test Harness', projectLine: 'Created synthetic tenant-isolation tests for object-level authorization and token validation.', experience: 'Security Engineer', experienceLine: 'Reviewed a service boundary and added regression tests for invalid credentials and cross-tenant access.' },
        { id: 'systems', name: 'Systems / Embedded', headline: 'Systems Software Engineer', focus: 'Explain resource lifetime, concurrency, hardware/software interfaces, debugging, and performance evidence. Keep proprietary platform details out of public resumes.', skills: 'Languages: C, C++, Python\nSystems: Linux, concurrency, networking\nTools: GDB, sanitizers, profiling', project: 'Bounded Work Queue', projectLine: 'Implemented a producer-consumer queue with graceful shutdown and contention-focused tests.', experience: 'Systems Engineer', experienceLine: 'Diagnosed a resource-lifetime defect and added a regression test for the relevant shutdown ordering.' },
        { id: 'lead', name: 'Senior / Technical Lead', headline: 'Senior Software Engineer', focus: 'Show technical scope, decisions, cross-team influence, mentoring, and verified outcomes. Separate your own actions from the broader team achievement.', skills: 'Engineering: Architecture, API design, reliability\nLeadership: Technical planning, mentoring, reviews\nTools: Your strongest production stack', project: 'Migration Design Case Study', projectLine: 'Documented a staged migration with compatibility checks, rollback criteria, and operational ownership.', experience: 'Senior Software Engineer', experienceLine: 'Led a design review that clarified ownership, failure boundaries, and a testable rollout plan.' },
        { id: 'research', name: 'Research / Academic', headline: 'Research Engineer', focus: 'Use the length your actual work requires. Include research questions, methods, reproducible artifacts, and correctly attributed publications rather than forcing an academic CV into one page.', skills: 'Languages: Python, C++\nResearch: Experimental design, evaluation, reproducibility\nTools: PyTorch, LaTeX, Git', project: 'Reproducible Model Benchmark', projectLine: 'Built a controlled comparison with documented datasets, parameters, baselines, and limitations.', experience: 'Research Assistant', experienceLine: 'Implemented an experiment pipeline and reviewed reproducibility, data provenance, and error analysis.', educationFirst: true },
        { id: 'intern', name: 'Student / First Internship', headline: 'Computer Science Student', focus: 'Use coursework, clubs, and substantial projects as evidence. Do not invent paid experience. State your contribution and what you tested.', skills: 'Languages: Python, JavaScript, SQL\nFoundations: Algorithms, OOP, databases\nTools: Git, Linux, unit testing', project: 'Student Resource Exchange', projectLine: 'Built a searchable resource catalogue with input validation and tests for permissions and missing records.', experience: 'Student Developer', experienceLine: 'Maintained a club website and reviewed accessibility, links, and mobile layouts before each release.', educationFirst: true },
        { id: 'career-change', name: 'Career Switch / Lateral', headline: 'Software Developer', focus: 'Connect transferable skills to the target role. Keep earlier experience truthful, and make recent engineering work independently inspectable.', skills: 'Languages: Python, JavaScript, SQL\nEngineering: REST APIs, React, PostgreSQL\nTransferable skills: Process analysis, stakeholder communication', project: 'Operations Workflow API', projectLine: 'Implemented a workflow API with role-based permissions, audit events, and integration tests.', experience: 'Application Developer', experienceLine: 'Translated an operations workflow into documented API contracts and a validated migration plan.' },
        { id: 'engineering-manager', name: 'Software Engineering Manager', headline: 'Software Engineering Manager', focus: 'Include team scope, coaching, hiring, delivery, reliability, and cross-functional decisions. Distinguish team outcomes from your direct contribution.', skills: 'Leadership: Coaching, hiring, career development\nExecution: Roadmaps, delivery planning, incident learning\nEngineering: System design, service ownership, technical reviews', project: 'Engineering Operating Model', projectLine: 'Introduced ownership maps, risk reviews, and release criteria agreed with product and operations.', experience: 'Engineering Manager', experienceLine: 'Led an eight-engineer platform team, balancing roadmap delivery, reliability work, and individual development.' },
        { id: 'director', name: 'Director of Engineering', headline: 'Director of Engineering', focus: 'Explain the organizations and decisions you owned, not just a larger list of technologies. Cover investment choices, leadership development, delivery, and business context.', skills: 'Organization: Multi-team leadership, succession, hiring\nStrategy: Portfolio planning, platform investment, risk\nExecution: Delivery health, reliability, cross-functional alignment', project: 'Platform Consolidation Strategy', projectLine: 'Developed a phased consolidation plan with customer impact, migration gates, ownership, and retirement criteria.', experience: 'Director of Engineering', experienceLine: 'Aligned three engineering teams around a shared platform roadmap and explicit product and operational priorities.' },
        { id: 'principal', name: 'Staff / Principal Engineer', headline: 'Principal Software Engineer', focus: 'Show cross-team technical influence, decisions under uncertainty, migration strategy, and durable engineering improvements. Provide workload context for performance claims.', skills: 'Architecture: Distributed systems, API evolution, storage\nInfluence: Design reviews, technical strategy, mentoring\nEngineering: Reliability, performance analysis, migration planning', project: 'Service Boundary Modernization', projectLine: 'Designed versioned service boundaries with compatibility checks, migration telemetry, and rollback criteria.', experience: 'Principal Software Engineer', experienceLine: 'Led architecture reviews across service teams to clarify consistency guarantees, ownership, and failure recovery.' },
        { id: 'qa', name: 'QA / SDET', headline: 'Software Development Engineer in Test', focus: 'Show risk-based test design, maintainable automation, failure diagnosis, release confidence, and collaboration. Test-count growth alone is not an outcome.', skills: 'Languages: TypeScript, Python, SQL\nTesting: Playwright, API testing, contract tests\nQuality: CI diagnostics, accessibility, release risk', project: 'API Contract Test Platform', projectLine: 'Built versioned contract checks and a synthetic-data harness for authentication, pagination, and failure cases.', experience: 'Software Engineer in Test', experienceLine: 'Created risk-based regression coverage for critical workflows and documented reproducible defect reports.' },
        { id: 'designer', name: 'Product / UX Designer', headline: 'Product Designer', focus: 'Link to case studies that show the problem, research, design decisions, accessibility, and observed outcomes. Distinguish personal work from the team contribution.', skills: 'Design: Interaction design, design systems, prototyping\nResearch: Interviews, usability studies, synthesis\nTools: Figma, accessibility audits, product analytics', project: 'Accessible Onboarding Redesign', projectLine: 'Mapped onboarding failure points and tested revised interaction flows with representative users.', experience: 'Product Designer', experienceLine: 'Partnered with engineering and product to define accessible interaction patterns and release-ready specifications.' },
        { id: 'analyst', name: 'Data / BI Analyst', headline: 'Data Analyst', focus: 'State the business question, data grain, method, validation, and resulting decision. Avoid causal claims from observational dashboards alone.', skills: 'Analysis: SQL, Python, spreadsheets\nBI: Power BI, Tableau, data modeling\nMethods: Cohort analysis, experimentation, data quality', project: 'Customer Retention Analysis', projectLine: 'Defined retention cohorts and reconciled SQL outputs against raw events before building a decision dashboard.', experience: 'Data Analyst', experienceLine: 'Translated business questions into documented metrics and SQL models with duplicate and missing-data checks.' },
        { id: 'product-manager', name: 'Product Manager', headline: 'Technical Product Manager', focus: 'Show customer problems, prioritization, product decisions, partnership with engineering, and supportable outcomes. Avoid presenting a shipped feature as impact by itself.', skills: 'Product: Discovery, roadmaps, prioritization\nAnalysis: SQL, experiment design, product metrics\nCollaboration: Engineering, design, customer research', project: 'Developer Onboarding Strategy', projectLine: 'Prioritized onboarding friction using interviews, funnel analysis, and a measurable experiment plan.', experience: 'Technical Product Manager', experienceLine: 'Defined a developer-tools roadmap around validated user problems and negotiated delivery scope with engineering.' },
        { id: 'business-analyst', name: 'Business Analyst', headline: 'Business Analyst', focus: 'Describe the problem, stakeholder needs, process decisions, acceptance criteria, and validation. Keep responsibilities distinct from delivered outcomes.', skills: 'Analysis: Requirements, process modeling, SQL\nDelivery: User stories, acceptance criteria, UAT\nTools: BPMN, spreadsheets, Jira, stakeholder workshops', project: 'Order Reconciliation Workflow', projectLine: 'Mapped reconciliation exceptions and defined testable acceptance criteria with finance and engineering.', experience: 'Business Analyst', experienceLine: 'Translated stakeholder interviews into prioritized requirements, process maps, and traceable acceptance tests.' },
        { id: 'cloud', name: 'Cloud / Solutions Architect', headline: 'Cloud Solutions Architect', focus: 'State workload, reliability, security, cost, and migration constraints. Separate certifications from hands-on architecture and delivery evidence.', skills: 'Cloud: Azure, AWS, infrastructure as code\nArchitecture: Networking, IAM, observability\nDelivery: Migration planning, disaster recovery, cost analysis', project: 'Resilient Workload Reference Design', projectLine: 'Designed a reference workload with least-privilege access, recovery exercises, and documented cost assumptions.', experience: 'Cloud Solutions Architect', experienceLine: 'Led workload assessments and translated reliability, security, and cost requirements into migration designs.' },
        { id: 'technical-writer', name: 'Technical Writer', headline: 'Technical Writer and Documentation Engineer', focus: 'Link to writing samples and explain audience, information architecture, technical validation, and maintenance. Do not publish internal or confidential documentation.', skills: 'Writing: API documentation, tutorials, information architecture\nEngineering: Git, Markdown, OpenAPI, code samples\nQuality: Documentation tests, accessibility, user research', project: 'Developer Documentation Portal', projectLine: 'Organized API references and task-based tutorials with tested code samples and a versioned review workflow.', experience: 'Technical Writer', experienceLine: 'Turned complex service behavior into task-based guides and validated examples with engineering and support.' }
    ];

    const roleDetails = {
        graduate: { summary: 'Computer science graduate with hands-on projects in APIs, databases, and automated testing. Comfortable explaining implementation choices, debugging failures, and collaborating through code review.', evidence: ['Implemented a paginated API endpoint and verified boundary cases with integration tests.', 'Investigated failing CI checks and documented the reproduction and resolution for the team.'], projectDetails: ['Modeled prerequisite relationships and rejected circular dependencies before persisting a plan.', 'Added a clear README, seeded demo data, and tests for incomplete and conflicting inputs.'], secondProject: 'Campus Placement Tracker', secondBullet: 'Built a SQL-backed application tracker with search, status history, and exportable summaries.' },
        backend: { summary: 'Backend engineer building reliable APIs and data services with Python, TypeScript, and PostgreSQL. Experienced in schema evolution, asynchronous processing, automated testing, and production troubleshooting.', evidence: ['Added idempotency keys and bounded retries to a background processing workflow.', 'Instrumented request latency and failure categories, then documented on-call diagnosis and rollback steps.'], projectDetails: ['Defined explicit task states and tested duplicate requests, worker interruption, and delayed delivery.', 'Compared index choices with representative queries and recorded the measurement method.'], secondProject: 'Inventory Reservation API', secondBullet: 'Used transactional updates to prevent overselling and added concurrent-request tests for reservation expiry.' },
        frontend: { summary: 'Frontend engineer focused on accessible product workflows, predictable state management, and maintainable component systems. Works with design and backend teams to turn ambiguous interactions into tested interfaces.', evidence: ['Defined loading, empty, error, and recovery states for a multi-step customer workflow.', 'Profiled a large results view and verified keyboard navigation and screen-reader labels.'], projectDetails: ['Tested filters, sorting, form errors, and browser navigation with Playwright.', 'Created reusable design tokens and verified layouts at phone, tablet, and desktop widths.'], secondProject: 'Accessible Component Library', secondBullet: 'Documented component states and added interaction tests for dialogs, menus, and form controls.' },
        'full-stack': { summary: 'Full-stack engineer delivering complete workflows across React interfaces, Node.js services, and relational data models. Focused on clear API contracts, secure authorization, test coverage, and operational handover.', evidence: ['Defined transaction boundaries for booking and cancellation to prevent inconsistent availability.', 'Added permission checks and end-to-end tests covering client validation and service failures.'], projectDetails: ['Modeled availability and cancellation rules in PostgreSQL transactions.', 'Implemented accessible forms, conflict messages, and repeatable integration tests.'], secondProject: 'Team Issue Workspace', secondBullet: 'Built role-based issue assignment, activity history, and a searchable workspace with API and UI tests.' },
        mobile: { summary: 'Mobile engineer building reliable Android and iOS experiences with attention to lifecycle, offline state, and accessibility. Comfortable tracing performance and crash reports back to reproducible device scenarios.', evidence: ['Implemented offline caching with explicit stale-data states and recoverable synchronization.', 'Validated app behavior during process recreation, interrupted requests, and changing connectivity.'], projectDetails: ['Persisted reading state through process restarts and tested duplicate sync events.', 'Audited text scaling, focus order, and screen-reader descriptions.'], secondProject: 'Travel Expense Companion', secondBullet: 'Implemented local-first expense entry with validated currency input and conflict-aware background synchronization.' },
        platform: { summary: 'Platform and reliability engineer improving service delivery, observability, and operational recovery. Builds automation that makes deployment behavior measurable and failure handling repeatable for service teams.', evidence: ['Defined service-level indicators and alert ownership with application teams.', 'Automated environment provisioning and validated disaster-recovery runbooks in a controlled environment.'], projectDetails: ['Modeled dependency failures and checked alert routing against a synthetic incident set.', 'Added a dashboard, a deployment checklist, and a rollback exercise with clear acceptance criteria.'], secondProject: 'Deployment Safety Pipeline', secondBullet: 'Implemented staged deployment gates with readiness checks, test evidence, and auditable rollback decisions.' },
        data: { summary: 'Data engineer building dependable batch and incremental pipelines with explicit data contracts, quality checks, and recovery procedures. Uses SQL and Python to turn event data into reproducible analytical models.', evidence: ['Designed replayable ingestion with deduplication keys and late-event handling.', 'Documented table grain, freshness expectations, lineage, and backfill ownership.'], projectDetails: ['Validated incremental results against a full rebuild on synthetic historical data.', 'Added row-count, uniqueness, nullability, and schema checks before publishing tables.'], secondProject: 'Data Quality Monitor', secondBullet: 'Created freshness and distribution checks with actionable failure messages and owner-specific runbooks.' },
        ml: { summary: 'Machine learning engineer building reproducible evaluation and serving workflows. Focused on leakage-resistant data splits, meaningful baselines, error analysis, and the latency and reliability constraints of production inference.', evidence: ['Versioned datasets and configurations so experiments could be repeated and compared.', 'Added input validation and monitored feature availability and serving failures.'], projectDetails: ['Separated evaluation queries from tuning data and recorded relevance labels and limitations.', 'Compared retrieval quality and latency before selecting a candidate approach.'], secondProject: 'Model Evaluation Service', secondBullet: 'Packaged a baseline model with deterministic preprocessing, batch evaluation, and tests for missing features.' },
        security: { summary: 'Security engineer working on application security, identity boundaries, and defensible remediation. Combines threat modeling, authorized testing, and regression coverage to make security requirements concrete for engineering teams.', evidence: ['Mapped trust boundaries and prioritized remediation by exploitability and business impact.', 'Reviewed least-privilege policies and verified fixes with repeatable synthetic tests.'], projectDetails: ['Covered expired credentials, missing claims, and cross-tenant object identifiers.', 'Documented scope, limitations, and responsible handling of test findings.'], secondProject: 'Secure Configuration Review', secondBullet: 'Built a defensive checker for deployment configuration with explicit severity, remediation, and false-positive handling.' },
        systems: { summary: 'Systems engineer working with C, C++, Linux, and concurrent software. Experienced in resource-lifetime analysis, failure reproduction, performance profiling, and writing tests around shutdown and recovery behavior.', evidence: ['Used sanitizers and structured traces to isolate memory and concurrency defects.', 'Documented ownership and shutdown invariants across a shared component boundary.'], projectDetails: ['Tested cancellation, queue saturation, concurrent shutdown, and ownership transfer.', 'Measured contention under a documented workload and recorded correctness trade-offs.'], secondProject: 'Storage Trace Analyzer', secondBullet: 'Built a parser for synthetic storage traces that correlates operations and flags inconsistent lifecycle ordering.' },
        lead: { summary: 'Senior engineer leading design and delivery across service boundaries. Combines hands-on implementation with architecture reviews, mentoring, and operational planning to make complex changes understandable and reversible.', evidence: ['Mentored engineers through design alternatives, review feedback, and incident follow-ups.', 'Coordinated compatibility testing and deployment ownership across dependent teams.'], projectDetails: ['Defined migration phases, validation datasets, and rollback conditions before implementation.', 'Recorded trade-offs and operational responsibilities in a reviewed decision log.'], secondProject: 'Service Ownership Framework', secondBullet: 'Established clear service contracts, escalation paths, and readiness criteria with product and operations partners.' },
        research: { summary: 'Research engineer developing reproducible experiments and evaluation tools. Interested in robust measurement, transparent baselines, and translating experimental findings into well-scoped engineering decisions.', evidence: ['Maintained versioned experiment configurations and reviewed dataset provenance.', 'Analyzed error patterns and documented conclusions separately from untested hypotheses.'], projectDetails: ['Published executable experiments, environment details, and expected output checks.', 'Reported confidence limits and failure cases alongside aggregate evaluation results.'], secondProject: 'Experiment Reproducibility Toolkit', secondBullet: 'Created configuration validation, dataset checksums, and repeatable result summaries for controlled studies.' },
        intern: { summary: 'Computer science student with practical coursework and independent projects in web development, databases, and testing. Seeking an internship focused on learning through implementation, debugging, and collaborative review.', evidence: ['Added automated checks for broken links and form validation before publishing updates.', 'Explained implementation decisions and test cases during peer project reviews.'], projectDetails: ['Designed the data model and implemented search, pagination, and duplicate-entry checks.', 'Prepared an accessible demo and setup instructions that classmates could reproduce.'], secondProject: 'Algorithm Visualizer', secondBullet: 'Implemented sorting and graph-traversal visualizations with deterministic examples and tests for empty inputs.' },
        'career-change': { summary: 'Software developer combining hands-on application projects with prior experience in operations analysis and stakeholder communication. Focused on translating real workflow constraints into tested, maintainable software.', evidence: ['Built a React interface with validation and clear recovery from service errors.', 'Used prior process-analysis experience to identify ambiguous rules before coding.'], projectDetails: ['Mapped permission rules into tests for allowed and denied actions.', 'Documented the transition from a spreadsheet workflow to a versioned service contract.'], secondProject: 'Personal Finance Dashboard', secondBullet: 'Built a CSV import and SQL reporting workflow with duplicate detection and reconciliation tests.' },
        'engineering-manager': { summary: 'Engineering manager with experience leading platform delivery, developing engineers, and partnering with product teams. Combines technical judgment with clear ownership, sustainable planning, and candid operational reviews.', evidence: ['Established regular coaching, role expectations, and development plans with individual engineers.', 'Partnered with product to prioritize customer work alongside security and reliability obligations.', 'Introduced incident reviews that assigned measurable follow-up actions without individual blame.'], projectDetails: ['Defined release readiness using test evidence, operational ownership, and rollback criteria.', 'Created a decision log to make priority changes and capacity trade-offs visible.'], secondProject: 'Engineering Growth Framework', secondBullet: 'Built a consistent onboarding and mentoring program with reviewed role expectations and feedback checkpoints.' },
        director: { summary: 'Engineering leader translating product strategy into sustainable multi-team execution. Experienced in organizational design, technical investment decisions, leadership development, and communicating delivery and operational risk.', evidence: ['Developed engineering managers through shared planning and leadership feedback routines.', 'Negotiated investment trade-offs with product, finance, and security stakeholders.', 'Established common operating reviews for customer impact, reliability, staffing, and delivery risk.'], projectDetails: ['Evaluated migration dependencies and the cost of maintaining parallel platforms.', 'Assigned executive and engineering ownership to each stage of the transition.'], secondProject: 'Technical Leadership Development', secondBullet: 'Created a cross-team architecture forum and a succession plan for critical engineering responsibilities.' },
        principal: { summary: 'Principal engineer shaping distributed-system architecture and cross-team technical direction. Focused on reducing ambiguity around contracts, consistency, resource ownership, and safe evolution of critical services.', evidence: ['Compared architecture alternatives using workload models, failure analysis, and prototype evidence.', 'Mentored senior engineers and created reusable design-review questions across teams.', 'Led a staged migration with compatibility checks and explicit operational rollback ownership.'], projectDetails: ['Separated immutable contracts from implementation choices and recorded their consumers.', 'Validated migration and recovery behavior under controlled dependency failures.'], secondProject: 'Performance Investigation Framework', secondBullet: 'Standardized benchmark datasets, tracing, and interpretation of latency and resource-utilization results.' },
        qa: { summary: 'Software engineer in test building maintainable automation and clear release-risk evidence. Experienced in API contracts, browser workflows, synthetic data, and diagnosing failures across client and service boundaries.', evidence: ['Replaced brittle timing-based UI checks with observable state and accessible selectors.', 'Separated environment failures from product defects in CI reports and triage guidance.'], projectDetails: ['Created negative cases for missing permissions, invalid payloads, and version mismatches.', 'Integrated deterministic fixtures and reproducible failure artifacts into CI.'], secondProject: 'Cross-Browser Regression Suite', secondBullet: 'Covered critical user journeys, keyboard access, and responsive layouts with stable test data and actionable reports.' },
        designer: { summary: 'Product designer translating user research into accessible, coherent workflows. Builds prototypes and design-system patterns that make interaction decisions testable and implementation details clear to engineering partners.', evidence: ['Synthesized interview and usability findings into prioritized workflow improvements.', 'Documented component behavior for validation, loading, error, and recovery states.'], projectDetails: ['Compared prototype alternatives against explicit usability tasks and accessibility criteria.', 'Documented research limitations and separated observed findings from design hypotheses.'], secondProject: 'Design System Accessibility Audit', secondBullet: 'Reviewed focus order, color contrast, typography, and component states with designers and frontend engineers.' },
        analyst: { summary: 'Data analyst turning ambiguous business questions into validated metrics and clear decision support. Experienced in SQL, cohort analysis, dashboard design, and communicating assumptions and limitations to stakeholders.', evidence: ['Documented metric definitions and reconciled reporting differences with source systems.', 'Built reusable analysis queries with checks for missing events, duplicate rows, and time boundaries.'], projectDetails: ['Separated first-use, repeat-use, and churn definitions before comparing cohorts.', 'Annotated changes in data collection that affected interpretation of the results.'], secondProject: 'Revenue Reconciliation Dashboard', secondBullet: 'Reconciled orders, payments, and refunds at the correct data grain before publishing weekly business summaries.' },
        'product-manager': { summary: 'Technical product manager connecting customer needs, engineering constraints, and measurable product decisions. Experienced in discovery, prioritization, experiment design, and aligning cross-functional teams around clear outcomes.', evidence: ['Defined success and guardrail metrics before committing to an experiment.', 'Reviewed customer feedback and adoption data to refine priorities after launch.', 'Partnered with engineering on technical dependencies, rollout risk, and support readiness.'], projectDetails: ['Mapped user segments and distinguished usability issues from missing capabilities.', 'Defined a phased release and a decision framework for expansion or rollback.'], secondProject: 'Product Discovery Repository', secondBullet: 'Connected interview evidence, opportunity assessments, and roadmap decisions in a versioned research repository.' },
        'business-analyst': { summary: 'Business analyst turning complex workflows into clear requirements and testable acceptance criteria. Experienced in stakeholder workshops, process mapping, data reconciliation, and supporting delivery through user acceptance testing.', evidence: ['Maintained traceability from requirements to implementation and user acceptance checks.', 'Resolved conflicting business rules by documenting decisions and their owners.'], projectDetails: ['Defined exception categories and the handoff between automated and manual processing.', 'Validated the proposed workflow with realistic synthetic scenarios and edge cases.'], secondProject: 'Customer Support Process Review', secondBullet: 'Mapped escalation paths and proposed measurable changes with agreed owners and acceptance criteria.' },
        cloud: { summary: 'Cloud solutions architect designing secure, observable, and recoverable workloads. Works with engineering and business teams to connect architecture choices to reliability, cost, governance, and migration constraints.', evidence: ['Defined least-privilege access and reviewed network boundaries with security stakeholders.', 'Validated backup restoration and deployment recovery in a representative test environment.', 'Documented cost drivers, capacity assumptions, and ownership after migration.'], projectDetails: ['Automated infrastructure deployment with versioned configuration and policy checks.', 'Documented availability assumptions, failure scenarios, and recovery objectives.'], secondProject: 'Cloud Cost Review Toolkit', secondBullet: 'Grouped resource costs by workload and ownership, then tested recommendations against performance and reliability needs.' },
        'technical-writer': { summary: 'Technical writer and documentation engineer creating clear, testable developer content. Combines audience research, information architecture, and hands-on example validation to keep documentation accurate as products evolve.', evidence: ['Added automated checks for code samples, internal links, and versioned API references.', 'Used support feedback to prioritize unclear workflows and missing recovery guidance.'], projectDetails: ['Separated conceptual explanations, task guides, and API reference material.', 'Introduced review ownership and deprecation notices for changing interfaces.'], secondProject: 'API Getting-Started Guide', secondBullet: 'Wrote and tested authentication, pagination, and failure-recovery examples against a synthetic demo service.' }
    };
    const earlyRoles = new Set(['graduate', 'intern']);
    const seniorRoles = new Set(['lead', 'principal', 'engineering-manager', 'director', 'cloud']);
    const levels = { fresher: 'Freshers & Students', lateral: 'Lateral / Career Switch', experienced: 'Experienced', manager: 'Engineering Leadership', academic: 'Research & Academic' };
    const sources = { bajaj: { name: 'Sourabh Bajaj Resume', license: 'MIT', url: 'https://github.com/sb2nov/resume', overleaf: 'https://www.overleaf.com/latex/templates/software-engineer-resume/gqxmqsvsbdjf' } };

    const companies = [
        { id: 'general', name: 'Big Tech / General', advice: 'Match the actual role requirements. Prefer clear evidence of ownership, implementation, testing, and results. No template guarantees ATS acceptance or an interview.' },
        { id: 'microsoft', name: 'Microsoft', advice: 'Use the role description to select relevant problem solving, design, coding, testing, and domain evidence. Be precise about your contribution; this is not an official Microsoft CV template.', url: 'https://careers.microsoft.com/v2/global/en/hiring-tips/technical-interviewing' },
        { id: 'google', name: 'Google', advice: 'Highlight relevant technical work and explain scope and outcomes with evidence. Confirm role and level requirements. This track is preparation guidance, not an employer-approved format.', url: 'https://www.google.com/about/careers/applications/how-we-hire/' },
        { id: 'amazon', name: 'Amazon', advice: 'Show ownership, customer context, technical decisions, and supportable results. Use real examples rather than adding Leadership Principle slogans to every bullet.', url: 'https://www.amazon.jobs/content/en/how-we-hire/sde-ii-interview-prep' },
        { id: 'meta', name: 'Meta', advice: 'Make product impact, implementation, collaboration, and engineering depth easy to find when relevant to the role. Do not imply a standard template or a verified screening formula.' },
        { id: 'apple', name: 'Apple', advice: 'Prioritize the specialization in the job description and show detail-oriented engineering and collaboration. Do not expose confidential product or hardware information.', url: 'https://www.apple.com/careers/us/work-at-apple.html' },
        { id: 'netflix', name: 'Netflix', advice: 'Connect technical decisions to the product, operational judgment, and your actual scope. Be candid about trade-offs and lessons instead of exaggerating scale.', url: 'https://jobs.netflix.com/culture' },
        { id: 'nvidia', name: 'NVIDIA', advice: 'For relevant roles, emphasize systems, performance, memory, concurrency, or ML-serving evidence. Include workload and measurement context for performance results.', url: 'https://www.nvidia.com/en-us/about-nvidia/careers/how-we-hire/' }
    ];

    const sectionNames = { summary: 'Summary', skills: 'Technical Skills', experience: 'Experience', projects: 'Projects', education: 'Education', certifications: 'Certifications', publications: 'Publications', awards: 'Awards and Leadership', languages: 'Languages', custom: 'Additional Experience' };
    const colors = ['#176b5b', '#245ca7', '#273541', '#a14337', '#574144', '#166875'];
    const findTemplate = id => templates.find(template => template.id === id) || templates[0];
    const findRole = id => roles.find(role => role.id === id) || roles[1];
    const findCompany = id => companies.find(company => company.id === id) || companies[0];

    function text(value, limit = 500) {
        if (value === undefined || value === null) return '';
        if (typeof value !== 'string') throw new Error('Text fields must contain text, not objects or numbers.');
        if (value.length > limit) throw new Error('A text field exceeds the ' + limit + '-character limit.');
        return value.replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g, '');
    }

    function safeLink(value) {
        if (!value || typeof value !== 'string') return null;
        const candidate = value.trim();
        if (/^[a-z][a-z0-9+.-]*:/i.test(candidate) && !/^https?:/i.test(candidate)) return null;
        try {
            const url = new URL(/^https?:\/\//i.test(candidate) ? candidate : 'https://' + candidate);
            if (!['http:', 'https:'].includes(url.protocol) || url.username || url.password || !url.hostname.includes('.')) return null;
            return url.href;
        } catch { return null; }
    }

    function newItem() {
        return { heading: '', subheading: '', location: '', start: '', end: '', url: '', bullets: [] };
    }

    function newSection(kind, id) {
        return { id: id || kind, kind, title: sectionNames[kind] || 'Additional Section', visible: true, content: '', items: ['summary', 'skills', 'languages'].includes(kind) ? [] : [newItem()] };
    }

    function normalizeResume(input) {
        if (!input || typeof input !== 'object' || Array.isArray(input) || input.version !== 1) throw new Error('Choose a CV Studio version 1 JSON document.');
        if (!input.basics || typeof input.basics !== 'object' || Array.isArray(input.basics)) throw new Error('The document is missing contact information.');
        if (!Array.isArray(input.sections) || input.sections.length > 16) throw new Error('A CV can contain up to 16 sections.');
        const ids = new Set();
        const sections = input.sections.map(section => {
            if (!section || !/^[a-z][a-z0-9-]{0,70}$/.test(section.id) || ids.has(section.id)) throw new Error('Section IDs must be unique letters, digits, and hyphens.');
            if (!Object.hasOwn(sectionNames, section.kind)) throw new Error('Unsupported section kind.');
            ids.add(section.id);
            const items = section.items || [];
            if (!Array.isArray(items) || items.length > 35) throw new Error('A section can contain up to 35 entries.');
            return {
                id: section.id, kind: section.kind, title: text(section.title || sectionNames[section.kind], 80), visible: section.visible !== false,
                content: text(section.content, 3500), items: items.map(item => {
                    if (!item || typeof item !== 'object') throw new Error('Invalid CV entry.');
                    if (!Array.isArray(item.bullets || []) || (item.bullets || []).length > 15) throw new Error('An entry can contain up to 15 bullets.');
                    return { heading: text(item.heading, 180), subheading: text(item.subheading, 180), location: text(item.location, 120), start: text(item.start, 40), end: text(item.end, 40), url: text(item.url, 350), bullets: (item.bullets || []).map(bullet => text(bullet, 700)) };
                })
            };
        });
        const basics = {};
        for (const field of ['name', 'headline', 'email', 'phone', 'location', 'website', 'linkedin', 'github']) basics[field] = text(input.basics[field], field === 'headline' ? 180 : 350);
        basics.photo = text(input.basics.photo, 240000);
        if (basics.photo && !/^data:image\/(png|jpeg);base64,[A-Za-z0-9+/]+={0,2}$/.test(basics.photo)) throw new Error('Photos must be local PNG or JPEG images.');
        if (input.example === true && basics.name === 'Alex Morgan' && basics.email === 'alex@example.com') {
            basics.name = 'Yasir Sharfi';
            basics.email = 'yasir.sharfi@example.com';
        }
        const settings = input.settings || {};
        const template = findTemplate(input.template);
        return {
            version: 1, title: text(input.title || 'Untitled CV', 100), template: template.id,
            role: findRole(input.role).id, company: findCompany(input.company).id, example: input.example === true,
            settings: { paper: settings.paper === 'LETTER' ? 'LETTER' : 'A4', fontSize: [9, 10, 11, 12].includes(settings.fontSize) ? settings.fontSize : 10, spacing: ['compact', 'regular', 'airy'].includes(settings.spacing) ? settings.spacing : template.density, accent: colors.includes(settings.accent) ? settings.accent : template.color, font: ['Lato', 'PlexSerif'].includes(settings.font) ? settings.font : template.font, margins: [32, 40, 48, 56].includes(settings.margins) ? settings.margins : 40, pageNumbers: settings.pageNumbers === true },
            basics, sections
        };
    }

    function starter(roleId = 'backend', blank = false) {
        const role = findRole(roleId);
        const details = roleDetails[role.id];
        const early = earlyRoles.has(role.id);
        const senior = seniorRoles.has(role.id);
        const template = role.id === 'research' ? 'research' : role.id === 'graduate' ? 'graduate' : 'classic';
        const sections = [newSection('summary'), newSection('skills'), newSection('experience'), newSection('projects'), newSection('education')];
        if (!blank) {
            sections[0].content = details.summary;
            sections[1].content = role.skills;
            sections[2].items = [{ ...newItem(), heading: role.experience, subheading: early ? 'Sample Innovation Lab' : 'Sample Product Co.', location: 'Bengaluru, India', start: early ? 'Jun 2025' : '2022', end: early ? 'Aug 2025' : 'Present', bullets: [role.experienceLine, ...details.evidence] }];
            if (senior || role.id === 'career-change') sections[2].items.push({ ...newItem(), heading: role.id === 'career-change' ? 'Operations Analyst' : role.id === 'director' ? 'Engineering Manager' : 'Software Engineer', subheading: 'Sample Technology Ltd.', location: 'Hyderabad, India', start: '2018', end: '2022', bullets: [role.id === 'career-change' ? 'Analyzed operational exceptions and documented workflows with finance and support stakeholders.' : 'Owned implementation and release validation for customer-facing service improvements.', 'Documented technical decisions, investigated incidents, and supported handover to the operating team.'] });
            sections[3].items = [
                { ...newItem(), heading: role.project, subheading: early ? 'Academic project' : 'Selected technical work', start: '2025', end: '2026', url: 'https://example.com/portfolio', bullets: [role.projectLine, ...details.projectDetails] },
                { ...newItem(), heading: details.secondProject, subheading: 'Independent portfolio project', start: '2024', end: '2025', bullets: [details.secondBullet] }
            ];
            sections[4].items = [{ ...newItem(), heading: ['designer', 'product-manager', 'business-analyst'].includes(role.id) ? 'Bachelor of Science' : 'B.Tech. in Computer Science', subheading: 'Sample Institute of Technology', location: 'India', start: early ? '2022' : senior ? '2014' : '2018', end: early ? '2026' : senior ? '2018' : '2022', bullets: early ? ['Relevant coursework: Algorithms, databases, operating systems, and software engineering.', 'Coordinated peer project reviews and maintained reproducible project documentation.'] : [] }];
            if (role.id === 'research') sections.push({ ...newSection('publications'), items: [{ ...newItem(), heading: 'Evaluating Robust Retrieval Under Noisy Queries', subheading: 'Y. Sharfi and collaborators | Illustrative research manuscript', start: '2026', bullets: ['Designed a controlled benchmark and documented limitations, error categories, and reproducibility artifacts.'] }] });
            if (['engineering-manager', 'director', 'lead', 'principal'].includes(role.id)) sections.push({ ...newSection('awards'), title: 'Leadership and Mentoring', items: [{ ...newItem(), heading: 'Technical mentoring and knowledge sharing', subheading: 'Sample engineering community', bullets: ['Facilitated design reviews and supported engineers in presenting trade-offs, evidence, and implementation risks.'] }] });
        }
        if (role.educationFirst) sections.splice(1, 0, sections.splice(sections.findIndex(section => section.kind === 'education'), 1)[0]);
        return normalizeResume({ version: 1, title: blank ? 'Untitled CV' : role.name + ' CV', template, role: role.id, company: 'general', example: !blank, settings: {}, basics: { name: blank ? '' : 'Yasir Sharfi', headline: blank ? '' : role.headline, email: blank ? '' : 'yasir.sharfi@example.com', phone: '', location: blank ? '' : 'Bengaluru, India', website: blank ? '' : 'https://example.com/portfolio', linkedin: '', github: '', photo: '' }, sections });
    }

    function starterForTemplate(id, blank = false) {
        const template = findTemplate(id);
        const document = applyTemplate(starter(template.role, blank), template.id);
        document.title = template.name + ' - ' + findRole(template.role).name;
        if (template.projectFirst) document.sections.splice(1, 0, document.sections.splice(document.sections.findIndex(section => section.kind === 'projects'), 1)[0]);
        return document;
    }

    function searchTemplates({ query = '', level = 'all', role = 'all', photo = false, layout = 'all' } = {}) {
        const words = String(query).toLowerCase().trim().split(/\s+/).filter(Boolean);
        return templates.filter(template => {
            if (level !== 'all' && template.level !== level) return false;
            if (role !== 'all' && template.role !== role) return false;
            if (photo && !template.photo) return false;
            if (layout !== 'all' && (layout === 'single') !== (template.layout === 'single')) return false;
            const profile = findRole(template.role);
            const searchable = [template.name, template.family, template.description, profile.name, profile.headline, profile.skills, levels[template.level], earlyRoles.has(profile.id) ? 'fresher fresher student junior campus entry-level' : '', template.photo ? 'photo portrait photograph' : 'simple no photo', template.source ? 'overleaf latex community' : ''].join(' ').toLowerCase();
            return words.every(word => searchable.includes(word));
        });
    }

    function applyTemplate(input, id) {
        const document = normalizeResume(input);
        const template = findTemplate(id);
        document.template = template.id;
        Object.assign(document.settings, { accent: template.color, font: template.font, spacing: template.density });
        return document;
    }

    function plainText(input) {
        const document = normalizeResume(input);
        const lines = [document.basics.name, document.basics.headline, ...['email', 'phone', 'location', 'website', 'linkedin', 'github'].map(field => document.basics[field])].filter(Boolean);
        for (const section of document.sections.filter(section => section.visible)) {
            lines.push('', section.title);
            if (section.content) lines.push(section.content);
            for (const item of section.items) {
                lines.push([item.heading, item.subheading, item.location, [item.start, item.end].filter(Boolean).join(' - ')].filter(Boolean).join(' | '));
                if (item.url) lines.push(item.url);
                lines.push(...item.bullets.filter(Boolean).map(bullet => '- ' + bullet));
            }
        }
        return lines.join('\n');
    }

    function review(input, jobText = '') {
        const document = normalizeResume(input);
        const findings = [];
        if (!document.basics.name.trim()) findings.push({ level: 'required', title: 'Add your name', detail: 'Use the name you want recruiters to see.' });
        if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(document.basics.email)) findings.push({ level: 'required', title: 'Check your email', detail: 'A valid contact email is missing.' });
        const content = plainText(document);
        if (/Example Company|Example University|Sample (Product|Technology|Institute|Innovation|engineering)|@example\.com|example\.com\/portfolio|illustrative research|Your city/i.test(content)) findings.push({ level: 'review', title: 'Replace example information', detail: 'Yasir Sharfi is the template identity. Sample employers, dates, and achievements are illustrative, not his biography. Only submit your own accurate details.' });
        const visible = document.sections.filter(section => section.visible);
        if (!visible.some(section => ['experience', 'projects'].includes(section.kind) && section.items.some(item => item.heading.trim()))) findings.push({ level: 'review', title: 'Add evidence of your work', detail: 'Include relevant experience or substantial projects with your specific contribution.' });
        const longBullets = visible.flatMap(section => section.items).flatMap(item => item.bullets).filter(bullet => bullet.trim().split(/\s+/).length > 45).length;
        if (longBullets) findings.push({ level: 'review', title: 'Shorten ' + longBullets + ' long bullet' + (longBullets === 1 ? '' : 's'), detail: 'Prioritize the action, technical context, and supportable result. Do not invent a metric to shorten the story.' });
        const links = [...['website', 'linkedin', 'github'].map(field => document.basics[field]), ...visible.flatMap(section => section.items.map(item => item.url))].filter(Boolean);
        if (links.some(link => !safeLink(link))) findings.push({ level: 'review', title: 'Check link format', detail: 'Only public HTTP/HTTPS links are exported as clickable links. Unsupported schemes remain plain text.' });
        if (findTemplate(document.template).layout !== 'single') findings.push({ level: 'note', title: 'Check two-column reading order', detail: 'Some parsing systems read columns differently. Prefer a single-column layout when the employer does not specify a format.' });
        if (document.basics.photo && findTemplate(document.template).photo) findings.push({ level: 'note', title: 'Check whether a photo is appropriate', detail: 'Photos are optional and can complicate parsing. Follow the employer and regional application requirements; a photo is not a hiring advantage score.' });
        findings.push({ level: 'note', title: 'Validate every achievement', detail: 'Use metrics only when you can explain the measurement and your contribution. No layout guarantees an interview or an ATS result.' });
        const stop = new Set('and the for with your this that from will are our you have has into about role team work years required experience skills preferred ability using knowledge strong excellent must should their them each also more such than some'.split(' '));
        const tokens = [...new Set(String(jobText).toLowerCase().match(/[a-z][a-z0-9+#.-]{2,}/g) || [])].filter(token => !stop.has(token)).slice(0, 45);
        const lower = content.toLowerCase();
        return { findings, wordCount: content.trim().split(/\s+/).filter(Boolean).length, matched: tokens.filter(token => lower.includes(token)), missing: tokens.filter(token => !lower.includes(token)) };
    }

    return { templates, roles, companies, colors, sectionNames, levels, sources, findTemplate, findRole, findCompany, safeLink, newItem, newSection, normalizeResume, starter, starterForTemplate, searchTemplates, applyTemplate, plainText, review };
});